-- Migration 001: Core structure for wo_standalone
-- Apply via Supabase Dashboard SQL Editor or CLI before first deploy.
-- Idempotent — safe to re-run.

BEGIN;

-- ─── Functions ───────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- ─── property ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS property (
    property_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT property_name_not_blank CHECK (BTRIM(name) <> '')
);

DROP TRIGGER IF EXISTS property_set_updated_at ON property;
CREATE TRIGGER property_set_updated_at
    BEFORE UPDATE ON property
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── phase ───────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS phase (
    phase_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    phase_code  TEXT NOT NULL,
    name        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT phase_code_not_blank CHECK (BTRIM(phase_code) <> ''),
    CONSTRAINT phase_property_code_unique UNIQUE (property_id, phase_code)
);

DROP TRIGGER IF EXISTS phase_set_updated_at ON phase;
CREATE TRIGGER phase_set_updated_at
    BEFORE UPDATE ON phase
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── building ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS building (
    building_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id   BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    phase_id      BIGINT NOT NULL REFERENCES phase(phase_id) ON DELETE RESTRICT,
    building_code TEXT NOT NULL,
    name          TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT building_code_not_blank CHECK (BTRIM(building_code) <> ''),
    CONSTRAINT building_phase_code_unique UNIQUE (phase_id, building_code)
);

DROP TRIGGER IF EXISTS building_set_updated_at ON building;
CREATE TRIGGER building_set_updated_at
    BEFORE UPDATE ON building
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── unit ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS unit (
    unit_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id      BIGINT NOT NULL REFERENCES property(property_id) ON DELETE RESTRICT,
    phase_id         BIGINT REFERENCES phase(phase_id) ON DELETE RESTRICT,
    building_id      BIGINT REFERENCES building(building_id) ON DELETE RESTRICT,
    unit_code_raw    TEXT NOT NULL,
    unit_code_norm   TEXT NOT NULL,
    unit_identity_key TEXT NOT NULL,
    floor_plan       TEXT,
    gross_sq_ft      INTEGER,
    has_carpet       BOOLEAN NOT NULL DEFAULT FALSE,
    has_wd_expected  BOOLEAN NOT NULL DEFAULT FALSE,
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unit_code_norm_not_blank CHECK (BTRIM(unit_code_norm) <> ''),
    CONSTRAINT unit_identity_key_not_blank CHECK (BTRIM(unit_identity_key) <> ''),
    CONSTRAINT unit_property_unit_code_unique UNIQUE (property_id, unit_code_norm),
    CONSTRAINT unit_property_identity_key_unique UNIQUE (property_id, unit_identity_key),
    CONSTRAINT unit_property_unit_unique UNIQUE (property_id, unit_id)
);

DROP TRIGGER IF EXISTS unit_set_updated_at ON unit;
CREATE TRIGGER unit_set_updated_at
    BEFORE UPDATE ON unit
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
