-- Migration 002: Unit movings — historical moving dates per unit.
-- Global table (no property_id): keyed on normalized unit_number text.
-- Idempotent — safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS unit_movings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_number TEXT NOT NULL,
    moving_date DATE NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unit_movings_unit_date_unique UNIQUE (unit_number, moving_date)
);

CREATE INDEX IF NOT EXISTS unit_movings_unit_number_idx ON unit_movings (unit_number);

COMMIT;
